name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Chat.gRPC.csproj Docker image
      run: cd ./src/Chat.gRPC/ && docker build . --file Dockerfile --tag grpc-chat-server:$(date +%s)
